
main:
  title: "Discover Your Musical Genius: Tell us about yourself!"
  test_acronym: "gms"
  background_color: "#fff"
  header_background : "fff"
  content_background: "fff"

mdt:
  title: "Melodic Discrimination"
  test_acronym: "mdt"
  background_color: "#519bfb"
  header_background : "083b55"
  content_background: "fafbfb"

bat:
  title: "Beat Alignment"
  test_acronym: "bat"
  background_color: "#3bacfc"
  header_background : "#f90047"
  content_background: "#fafbfb"


mpt:
  title: "Mistuning Perception"
  test_acronym: "mpt"
  background_color: "#84c642"
  header_background : "#083b55"
  content_background: "#fafbfb"
  gradient_background_color: "#85FFBD"
  gradient_background_image: "linear-gradient(45deg, #85FFBD 0%, #FFFB7D 100%);"



default:
  leaderboard: 'leaderboard.csv'
  cert_render_path: '/Users/sebsilas/gamifyr/tmp.Rmd'
  cert_location: '/Users/sebsilas/gamifyr/certificates/'
  take_training: FALSE
  cert_file: "extdata/certificate_template_pdf_v2.Rmd"

production:
  leaderboard: 'leaderboard.csv'
  cert_render_path: '/srv/shiny-server/create-certificate/tmp.Rmd'
  cert_location: '/srv/shiny-server/create-certificate/certificates/'
  take_training: TRUE
  cert_file: "extdata/certificate_template_pdf_v2_production.Rmd"

# config::get("trials", config = "production")
